name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || true

    - name: Build executable
      run: |
        pyinstaller --noconsole --onefile main.py
    
    - name: Make binary executable (macOS/Linux)
      if: runner.os != 'Windows'
      run: chmod +x dist/main

    - name: Rename binary
      run: |
        mkdir -p release
        cp dist/main* release/arcady-${{ matrix.os }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arcady-${{ matrix.os }}
        path: release/*

  release:
    needs: build-matrix
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/*

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
